CONDENSE_RESCALE=4 python3 -m torch.distributed.run --nproc_per_node=8 \
    --master_port=20005 --nnodes=1 --node_rank=$RANK --master_addr=127.0.0.1 \
    autoagents/train/train.py \
    --model_name_or_path meta-llama/Llama-2-13b-hf \
    --data_path path-to-sharegpt-data.json \
    --bf16 True \
    --output_dir output-directory-path \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 40 \
    --save_total_limit 20 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --model_max_length 4096 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
